version: "3"
services:
  backend:
    build: ./antrian-backend
    ports:
      - "5000:5000"
    volumes:
      - ./antrian-backend:/app

  frontend:
    build: ./antrian-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
